### PR TITLE
first version of auto-fep code

### PR DESCRIPTION
**Pull request by haz519**

### CODE REVIEW

**Review by nk53 — CHANGES_REQUESTED** [review]
There are a few issues that need to be resolved before I can accept this pull:
1. You have the auto_cgui project cloned inside of auto-fep. Please move these contents to the main auto_cgui directory instead. Similarly, `auto_cgui/auto-fep/ligands/*` should instead be in `auto_cgui/ligands/*`.
2. Please move your fep_cases to test_cases, and rename them so as not to conflict with MCA. E.g., `auto_cgui/auto-fep/fep_cases/basic.yml` could be renamed to `auto_cgui/test_cases/fep_basic.yml`.
3. Don't include `__pycache__/` in the commit. This is automatically generated by Python.

**Comment by haz519** [comment]
Done! Please check and let me know if I need to do other modifications.

Thank you,
Han

**Comment by nk53** [comment]
OK, this looks much better. There are minor changes I want to make, but I can do them myself.

**Comment by haz519** [comment]
What do I need to do now?

**Comment by nk53** [comment]
Are there any issues? Any bugs in your code that you know about? If so, let me know and I will help you solve them. Otherwise, your goal should be to make test cases for all 4 FEP submodules.

**Comment by haz519** [comment]
I can not go through my yaml file successfully. I think there are errors in
my FEPBrowserProcess.py, but I do not know how to fix it.

Below are my error messages:

Job "solvator" (-1) encountered an exception on step -1:
Traceback (most recent call last):
File "/Users/hanzhang/Desktop/auto_cgui/CGUIBrowserProcess.py", line 174,
in run
  self.init_system(test_case)
  File "/Users/hanzhang/Desktop/auto_cgui/FEPBrowserProcess.py", line 55,
in init_system
  self.go_next(fep_case['steps'][0]['wait_text'])
  File "/Users/hanzhang/Desktop/auto_cgui/CGUIBrowserProcess.py", line 117,
in go_next
  self.wait_text_multi([test_text, self.CHARMM_ERROR])
  File "/Users/hanzhang/Desktop/auto_cgui/CGUIBrowserProcess.py", line 244,
in wait_text_    mult    i
  if self.browser.is_text_present(text, wait_time):
  File
"/Users/hanzhang/opt/anaconda3/lib/python3.7/site-packages/splinter-0.13.0-py3.7.e
   gg/s    plinter/driver/webdriver/__init__.py", line 410, in
is_text_present
  self.driver.find_element_by_tag_name("body").text.index(text)b "solvator"
(-1) encoun

Any suggestion will be helpful.

Thank you,
Han

**Comment by nk53** [comment]
I'm unable to reproduce your error. Not because it works on my machine, but rather because it stops at a different stage. In my case, it hangs forever looking for 'Ligand ID', which doesn't seem to exist anywhere on the page.

Can you show me what your `config.yml` looks like?

**Comment by haz519** [comment]
I have attached my config.yml file to this email.

**Comment by nk53** [comment]
I don't see any attachment. Can you just paste your config here?

**Comment by haz519** [comment]
BASE_URL: http://beta.charmm-gui.org/
USER: testing
PASS: lammps

#WWW_DIR: /Users/hanzhang/Desktop/auto_cgui-master/data/www

**Comment by nk53** [comment]
I see. Can you describe what happens before Python crashes? Like I said, in my case, Python doesn't crash, but it instead reaches the "Set Pair Options" page (step=1) of relative ligand solvator. It waits for "Ligand ID", but this does not appear on the page anywhere, so the program hangs.

**Comment by haz519** [comment]
In my case, it also does not  crash. But just cannot  go to the next step
automatically. And the error message just said there is something wrong in
the 55 line of FEPBrowserProcess.py file.

**Comment by nk53** [comment]
OK. The problem is that you are waiting for the wrong text. Ligand ID does not occur on the page. Pick something else.

**Comment by haz519** [comment]
I will check!! Thank you!

**Comment by haz519** [comment]
Hi Nathan,

I have finished absolute ligand solvator and relative ligand solvator. But
I have a question here. If I want to change something in the front page,
where should I add commands in the yaml file? Because it would go to the
second page automatically after I upload several mol2 files in the front
page.

I am doing the absolute ligand binder sub-module right now. I have a
question about front page regarding this sub-module. It is different from
solvators sub-modules and I need to upload a PDB file in the binder
sub-module. In my opinion, the code should be similar to the code of
solvator sub-module because they both need to upload something (mol2 or
PDB). So I used similar code here. However, it gives me an error message
below:
splinter.exceptions.ElementDoesNotExist: no elements could be found with
name "files[]"

I am not sure where is the problem here. If you need my code, please let me
know.

Thank you,
Han

**Comment by nk53** [comment]
What front page are you talking about? `input/asolvating` or `input/afes.abinding`?

**Comment by haz519** [comment]
Input/afes.abinding

**Comment by nk53** [comment]
I just realized I never responded to you .... Do you still need help with this?

**Comment by haz519** [comment]
Thanks Nathan, I already finished and shared my code with you.

**Pull request merged**
