### PR TITLE
auto_cgui_fep

### PR DESCRIPTION
**Pull request by haz519**
second version of FEP

### CODE REVIEW

**Comment by nk53** [comment]
There would be merge conflicts with this pull request. Did you remember to sync your fork to current auto-cgui?

Please read this: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

You may also need to see this, in case syncing your fork results in a merge conflict: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/addressing-merge-conflicts

Let me know if you have any trouble.

**Comment by haz519** [comment]
Hi Nathan,

I copied my fork again to my local and manually added my modified scripts.
And then I used git add, commit and so on. After that I asked for a pull
request.

After following those steps, it had a merge conflict?

I will check them!

Thank you,
Han

**Comment by haz519** [comment]
Hi Nathan,

I am checking the conflicts of this pull request. However, I did not see
any conflicts when I clicked pull requests history of my fork (please see
the attached figure). There would be a resolve conflict button if there are
conflicts which are mentioned in
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github.
Please let me know if you have problem to see my code.
[image: Screen Shot 2020-06-05 at 8.27.04 AM.png]

Thanks,
Han

**Comment by nk53** [comment]
Well, there were merging issues, but I guess I had to deal with it. This pull request is merged now. Please sync your fork to mine again.

**Comment by haz519** [comment]
Done with sync my fork to yours. If I understand correctly, I need to sync
my fork first if I want to push something next time?

Thank you,
Han

**Pull request merged**
